name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: ./actions/setup-node
      - run: pnpm build
      - name: Publish to npm
        run: pnpm run publish-ci ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
